<h1>TextAPP.js</h1>
    <span>Some functions to manage texts and contents on different languages in the application.</span>
    <spa>These functions are in support of /system/module/Text/php/Text.php and /system/module/Text/php/Text.php classed and are meaningless in separate usage.</spa>
    <span>TextAPP.js is auto included only when user of type admin is logged in the system.</span>
    <span>Location: system/module/Text/js/TextAPP.js</span>
    
    <h3>TextAPP.insertPaste</h3>
        <span>Inserts pasted text from a popup paste window generated by TextAPP.pasteText function.</span>
        <ul>
            <li>
                <h4>TextAPP.insertPaste(writePosition)</h4>
                <p>This function is in support of TextAPP.pasteText and can not be used separately.</p>
            </li>
        </ul>
        
    <h3>TextAPP.pasteText</h3>
        <span>Detects paste event and creates a popup window with options.</span>
        <span>Paste as plain text and Paste with styles options are available.</span>
        <span>This function is auto included in TextAPP.showWysiwyg function.</span>
        <ul>
            <li>
                <h4>TextAPP.pasteText(event)</h4>
                <p>If paste is detected inside an text Wysiwyg field, creates popup window with paste options.</p>
            </li>
        </ul>
        
    <h3>TextAPP.showWysiwyg</h3>
        <span>Start text updater after CONTENTEDITABLE element is selected.</span>
        <ul>
            <li>
                <h4>TextAPP.showWysiwyg(event, id)</h4>
                <p>Select element to add eventlistener updater to it for edit with TextAPP.hideWysiwyg function. After element lose focus, TextAPP.hideWysiwyg saves the text and removes the eventlistener.</p>
            </li>
        </ul>
    
    <h3>TextAPP.hideWysiwyg</h3>
        <span>Save content in the database from elemenent attached with TextAPP.showWysiwyg function.</span>
        <ul>
            <li>
                <h4>TextAPP.hideWysiwyg(event)</h4>
                <p>TextAPP.hideWysiwyg saves the content after element lose focus and removes the eventlistener attached to it.</p>
            </li>
        </ul>
        
    <h3>TextAPP.updateText</h3>
        <span>Update the content when TextAPP.hideWysiwyg. This function is used inside TextAPP.hideWysiwyg.</span>
        <ul>
            <li>
                <h4>TextAPP.updateText(close=false)</h4>
                <p>Updates the selected content in the database. If close=close also closes the text updater.</p>
            </li>
        </ul>
        
    <h3>TextAPP.langChange</h3>
        <span>Changes the language for the selected content to be updated.</span>
        <span>Does nothing if the system has only one language installed.</span>
        <ul>
            <li>
                <h4>TextAPP.langChange(id, language, update=true)</h4>
                <span>id (integer): the id of the text database row to be updated.</span>
                <span>language (string): the language code for the update content. Example: en.</span>
                <span>update (boolean): if set to true, selects content on the choosen language for edit with TextAPP.hideWysiwyg.</span>
                <p>Retrieve data for the current update field to edit on another language.</p>
            </li>
        </ul>
        
    <h3>TextAPP.wysiwyg</h3>
        <span>Changes selected content based on the Wysiwyg editor actions.</span>
        <ul>
            <li>
                <h4>TextAPP.wysiwyg(command, value=false)</h4>
                <span>command (integer): the command to be executedon the selected content. Example: formatBlock</span>
                <span>value (string): specify the value for the command to apply or false if not necessary. Example: &lt;h1></span>
                <span>update (boolean): if set to true, selects content on the choosen language for edit with TextAPP.hideWysiwyg.</span>
                <p>Example: TextAPP.wysiwyg(formatBlock, '&lt;h2>')</p>
                <span>The above example will format the selected content in the contenteditable element as HEADING 2</span>
            </li>
        </ul>
        
    <h3>TextAPP.selectColor</h3>
        <span>Selects color from Wysiwyg panel and applies it to selected content.</span>